### ISSUE TITLE
legend format 功能无反应~求解！急！

### ISSUE THREAD

**Issue by buygaogao** [womkim/react-native-web-echarts#4]
我简单的 return 数值，有反应。但是如果放逻辑就没反应了。求解！ 急！
`option = {
    title : {
        text: '同名数量统计',
        subtext: '纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        // type: 'scroll',
        orient: 'vertical',
        right: 10,
        top: 20,
        bottom: 20,
        data: ['直达','营销广告','搜索引擎','邮件营销','联盟广告','视频广告','百度','谷歌','必应','其他'],
            formatter: function(name) {
                    var oa = option.series[0].data;
                    var num = oa.reduce(function (a, b) {
                        return a + b.value;
                    }, 0);
                    for (var i = 0; i < oa.length; i++) {
                        if (name == oa[i].name) {
                            console.log('name', name);
                            return result = name + ':  ' + oa[i].value +  ' ('  + (oa[i].value / num * 100).toFixed(2) + '%)';
                       }
                    }
            },
    },
    series : [
        {
            name:'访问来源',
            type:'pie',
            selectedMode: 'single',
            radius: [0, '30%'],

            label: {
                normal: {
                    position: 'inner'
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直达', selected:true},
                {value:679, name:'营销广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
};`

**Comment by womkim** [comment]
把写的function变成字符串试试


```
formatter: function () { ... }

// 写成

formatter: 'function () { ... }'
```

**Comment by womkim** [comment]
closed
